Add authenticated endpoint with tests
RagtagOpen/freefrom-map-backend pull request #52
Opened 2020-12-01 03:15 UTC by egiurleo

This PR builds off @DanielKim1's work in #47 

The only change is that this PR adds two tests demonstrating that auth works, along with some new environment variables and info in the README.

2020-12-01 03:16 UTC, egiurleo commented on tests/api/test_auth.py
> +                     "Cannot run test without AUTH0_CLIENT_ID and AUTH0_CLIENT_SECRET environment variables")
Skip the test if the AUTH0_CLIENT_ID and AUTH0_CLIENT_SECRET env variables are `None` or empty strings.

2020-12-01 14:09 UTC, egiurleo commented on tests/api/test_auth.py
> +    jwt = json.loads(jwt_response.text)['access_token']
I used this tutorial to figure out how to generate a JWT: https://auth0.com/blog/using-python-flask-and-angular-to-build-modern-web-apps-part-2/

2020-12-04 01:10 UTC, JZenk requested changes

2020-12-05 22:35 UTC, egiurleo commented on tests/api/test_auth.py
> +                     "Cannot run test without AUTH0_CLIENT_ID and AUTH0_CLIENT_SECRET environment variables")
@JZenk Good call! For some reason `requests` didn't end up in the `requirements.txt` file. Could you try re-running `pip install -r requirements.txt` and running the tests again?

2020-12-06 01:04 UTC, egiurleo commented on tests/api/test_auth.py
> +                     "Cannot run test without AUTH0_CLIENT_ID and AUTH0_CLIENT_SECRET environment variables")
And to be clear, please pull the changes I made first :)

2020-12-06 21:20 UTC, JZenk commented on tests/api/test_auth.py
> +                     "Cannot run test without AUTH0_CLIENT_ID and AUTH0_CLIENT_SECRET environment variables")
Huzzah! It now skips!

```bash
root@cc19da0e08ac:/app# python3 -m unittest
s.........................
----------------------------------------------------------------------
Ran 26 tests in 0.963s

OK (skipped=1)
```

2020-12-06 21:35 UTC, JZenk approved these changes
🏆 

I need to be added to Auth0 to fully test, but I am approving because the implementation is the same as the Auth0 howto.

Aka public APIs still work, private API fails as expected.

2020-12-07 01:02 UTC, merged